-- Portfolio CMS schema for the Next.js app.
-- Run this in Supabase SQL editor before using /admin and dynamic site content.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  profile_name text not null,
  profile_image_url text not null,
  resume_url text not null,
  email text not null,
  behance_url text not null,
  linkedin_url text not null,
  hero_primary_text text not null,
  hero_secondary_text text not null,
  contact_title text not null,
  contact_intro_text text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  image_url text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.designs (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null,
  url text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.works (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  technologies text[] not null default '{}',
  figma_url text not null,
  demo_url text not null default '',
  image_url text not null,
  available boolean not null default true,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  date_label text not null,
  url text not null,
  available boolean not null default true,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_site_settings_updated_at on public.site_settings;
create trigger trg_site_settings_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_songs_updated_at on public.songs;
create trigger trg_songs_updated_at
before update on public.songs
for each row execute function public.set_updated_at();

drop trigger if exists trg_designs_updated_at on public.designs;
create trigger trg_designs_updated_at
before update on public.designs
for each row execute function public.set_updated_at();

drop trigger if exists trg_works_updated_at on public.works;
create trigger trg_works_updated_at
before update on public.works
for each row execute function public.set_updated_at();

drop trigger if exists trg_blogs_updated_at on public.blogs;
create trigger trg_blogs_updated_at
before update on public.blogs
for each row execute function public.set_updated_at();

alter table public.site_settings enable row level security;
alter table public.songs enable row level security;
alter table public.designs enable row level security;
alter table public.works enable row level security;
alter table public.blogs enable row level security;

drop policy if exists "Public read site settings" on public.site_settings;
create policy "Public read site settings"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Public read songs" on public.songs;
create policy "Public read songs"
on public.songs
for select
to anon, authenticated
using (true);

drop policy if exists "Public read designs" on public.designs;
create policy "Public read designs"
on public.designs
for select
to anon, authenticated
using (true);

drop policy if exists "Public read works" on public.works;
create policy "Public read works"
on public.works
for select
to anon, authenticated
using (true);

drop policy if exists "Public read blogs" on public.blogs;
create policy "Public read blogs"
on public.blogs
for select
to anon, authenticated
using (true);

insert into public.site_settings (
  id,
  profile_name,
  profile_image_url,
  resume_url,
  email,
  behance_url,
  linkedin_url,
  hero_primary_text,
  hero_secondary_text,
  contact_title,
  contact_intro_text
)
values (
  1,
  'ABI KRISHNA',
  '/Abikrishna T.jpeg',
  'https://resolute-theater-bd2.notion.site/Resume-1b9a8cfceff181759799cb9305ecf476?source=copy_link',
  'abikrishna15@gmail.com',
  'https://www.behance.net/abikrishna15',
  'https://www.linkedin.com/in/abi-krishna-15abi/',
  'Graphic & UI/UX Designer, shaping brands and digital experiences.',
  'Designing interfaces with purpose, available for freelance & collaborations.',
  'Let''s Connect',
  'Let''s chat over ideas, design, or coffee.'
)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('portfolio-assets', 'portfolio-assets', true)
on conflict (id) do nothing;

drop policy if exists "Public read portfolio assets" on storage.objects;
create policy "Public read portfolio assets"
on storage.objects
for select
to public
using (bucket_id = 'portfolio-assets');
